version: '3.7'

services:

  db:
    container_name: database
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file:
      - database.env

  phpmyadmin:
    container_name: admin
    image: phpmyadmin
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      - 8081:80
    volumes:
      - /sessions

